function data = formatData(k,lag,n,T,ts,coeff,mu,explained,coeffbar,mubar,explained_bar,N_STATE_PC,A,SS_A,W,H,SS_H,Q,Explained_Mean,Explained_Trials,xbar,x,z)
%FORMATDATA Put data struct into stereotyped struct format
%
%  data = kal.formatData(...);
%
% Inputs
%  Basically everything that we want to save from `kal.kInit__`

data = struct(...
   'k',k,...
   'lag',lag,...
   'nTrials',n,...
   'samplesPerTrial',sum(T)/n,...
   'ts',ts(1:(sum(T)/n)),...
   'fs',1/nanmean(diff(ts(1:5))*1e-3),...
   't_all',ts,...
   'coeff',coeff,...
   'mu',mu,...
   'explained',explained,...
   'coeffbar',coeffbar,...
   'mubar',mubar,...
   'explained_bar',explained_bar,...
   'N_STATE_PC',N_STATE_PC,...
   'A',A,...
   'SS_A',SS_A,...
   'W',W,...
   'R2_A',SS_A.Total.Rsquared,...
   'H',H,...
   'SS_H',SS_H,...
   'Q',Q,...
   'R2_H',SS_H.Total.Rsquared);
data.Mask = T;
data.Explained_Mean = Explained_Mean;
data.Explained_Trials = Explained_Trials;
data.Xbar =xbar;
data.X = x;
data.Z = z;

end